### ISSUE TITLE
Add trust-dns-proto as a dependency

### ISSUE THREAD

**Issue by jan53n** [leshow/nailgun#23]
Hi, why is trust-dns-proto in the libs/ directory instead of using it as a dependency in the Cargo.toml file.

[https://crates.io/crates/trust-dns-proto](https://crates.io/crates/trust-dns-proto)

**Comment by leshow** [comment]
I know you closed this, but I'll answer anyway. Because it's been modified! 

The problem is that not all the generator types construct a valid `Message`, some of them, like the `randompkt` type, just make a `Vec<u8>`. The `trust-dns-proto` library has no way to send data that's not a `Message`, which makes sense for their API. You most likely don't want to send an invalid message. But if I want to copy that functionality from flamethrower, that's what I need... therefore the lib got copied & modified.

Maybe the `randompkt` generator is not useful, and maybe it will be removed and I will just pull in trust-dns as a dependency, I'm not sure yet.

**Comment by jan53n** [comment]
thanks for the answer, i was just curious (thought i asked the wrong question)
